#index:
#    path: /
#    controller: App\Controller\DefaultController::index
    # config/routes.yaml
    
# api/config/routes.yaml
authentication_token:
    path: /api/authentication_token
    methods: ['POST']
api:
    path: /api/test
    controller: App\Controller\api\apiController::api
    methods: ['POST']